### ISSUE TITLE
Compile target error

### ISSUE THREAD

**Issue by mindhells** [InvadingOctopus/octopuskit#10]
**Category:** 'Compilation'

**Describe the bug**
When I try to archive my iOS App, just after including this repo as a swift package dependency I get this error several time:

````
error: error reading dependency file '/Users/alberto/Library/Developer/Xcode/DerivedData/OctopusKitPoC-efudzfgceuckifblpxhfvqbvjsuy/Build/Intermediates.noindex/ArchiveIntermediates/OctopusKitPoC/IntermediateBuildFilesPath/OctopusKit.build/Release-iphoneos/OctopusKit.build/Objects-normal/arm64/OctopusKit-master.d': unexpected character in prerequisites at position 14049458 (in target 'OctopusKit' from project 'OctopusKit')
````
Then the archive generated is under the "other items" category inside the Organizer.

**To Reproduce**
1. Start with a new 'iOS App SwiftUI' project
2. Add this project as swift package dependency (development branch)
3. In Xcode, Product->Archive
4. Check the build process output

**Expected behavior**
Have a valid archive to distribute under the "iOS Apps" category in the Organizer.

**Screenshots**

![Captura de pantalla 2020-09-25 a las 17 20 34](https://user-images.githubusercontent.com/1893197/94291442-8790be80-ff53-11ea-9d5d-7287305d11f1.png)

![Captura de pantalla 2020-09-25 a las 17 20 17](https://user-images.githubusercontent.com/1893197/94291425-82cc0a80-ff53-11ea-99b0-3bc4c834e2c2.png)

**Build Environment (what you're developing on)**
    - OctopusKit Version: '4.0.0.beta3 -  development branch'
    - macOS Version: '10.15.6 (19G2021)'
    - Xcode Version: '12.0 (12A7209)'
    - Swift Version: '5'
 
**Target Device (what you're compiling for)**
    - Device: 'iPhone, iPad'
    - Target OS Version: 'iOS14.0'

**Comment by ShinryakuTako** [comment]
I’ll take a look into it and get back to you.

**Comment by codebendr-product-designer** [comment]
this library looks perfect for my next project...

any updates on this?.

**Comment by ShinryakuTako** [comment]
Sorry! I'm sort of on a vacation and my Mac is damaged; I haven't even gotten around to firing up Xcode yet :(

I'll definitely look into it before the weekend is over.

**Comment by ShinryakuTako** [comment]
@mindhells @codebendr-product-designer Please try archiving now.

The problem seemed to be arising from a naming conflict between `OKHighScoreChart.swift` and `OKHighScoreChart.xcdatamodeld`, both of which aren't actually used in OctopusKit yet.

I've removed `OKHighScoreChart.xcdatamodeld` from the package, and now a new project + OctopusKit is archiving for me without any issues in Xcode 12.0.1 (12A7300)

**Comment by codebendr-product-designer** [comment]
Thanks for the quick fix.
