### ISSUE TITLE
OK v3.2.x Migration Guide

### ISSUE THREAD

**Issue by chessboy** [InvadingOctopus/octopuskit#12]
- Category: Documentation
- Target Platform: macOS
 
I'm excited about OK v4.0 and just wondering if there will be a migration guide... my project is fairly big. I will poke around now on a new branch and see if I can figure it out, but a guide would be super awesome!  BTW, I am now supporting you on Patreon – Code Collaborator level. Hoping to make great things with you, ShinryakuTako, if that is your real name ;)

**Comment by chessboy** [comment]
oof... upgrading to your `/develop` branch requires macOS 11 for a minimum deployment target. As I'm still on macOS 10.15, I guess I'll have to wait.

`Compiling for macOS 10.15, but module 'OctopusKit' has a minimum deployment target of macOS 11.0`

**Comment by ShinryakuTako** [comment]
Thanks for becoming a patron!!! ＼(＾▽＾)／

Writing a migration guide or maintaining backwards compatibility is difficult for me as the sole developer on a hobby project 😖 as I'd rather be adding missing features and supporting the latest systems whenever I have the time and focus to work on it, but I could help you out on Discord! (server link is in the ReadMe)

In the meantime, you can try an older release/tag, or manually edit the `Package.swift` manifest to support older OS versions.

**Comment by chessboy** [comment]
Glad to be aboard this rocket ship! Yeah, that makes a lot of sense. Will give it a shot and contact you outside of github if I need to. Thanks for everything.
