### ISSUE TITLE
Unable to use package in Swift Playgrounds for iPad due to Catalyst warnings

### ISSUE THREAD

**Issue by transat** [InvadingOctopus/octopuskit#14]
**Category:** 'Behavior'

**Describe the bug**
The package causes some bugs when loaded in Swift Playgrounds for iPad. I believe it's because some files need `!targetEnvironment(macCatalyst)` added alongside the `#if canImport(AppKit)`.

**Comment by ShinryakuTako** [comment]
Sorry for the late reply, will look into it!

**Comment by ShinryakuTako** [comment]
Sorry if anyone was still waiting.. I have switched to Godot and have no plans to continue work on OctopusKit. 🥲
