### ISSUE TITLE
Hi, your template file no longer works with the latest version. It is no longer applicable. 

### ISSUE THREAD

**Issue by StarSkyK** [InvadingOctopus/octopuskit#16]
**Describe the bug**
Hi, your template file no longer works with the latest version. It is no longer applicable. For example, OKGameState needs to be changed to OctopusGameState now.

**Expected behavior**
Hopefully the template files are updated to the latest version

Thank you for all your hard work. 😄

**Comment by StarSkyK** [comment]
![image](https://github.com/InvadingOctopus/octopuskit/assets/23426094/27c83cfc-03de-4b59-bcd3-69e15c193da9)

Some warnings were found, but they don't seem to affect the operation. Does it need to be fixed?

**Comment by ShinryakuTako** [comment]
The "OK" prefix is the new one and matches the standard convention, as in Apple's APIs. The "Octopus" prefix version were replaced by aliases to the OK ones, but maybe I missed some.

As for the SwiftUI stuff, it's in need for a overhaul but I haven't been able to get around to it, or even figured out how best to do it and where to start 🥲
