### ISSUE TITLE
'KeyboardEventComponent' is unavailable in iOS

### ISSUE THREAD

**Issue by Harry-Harrison** [InvadingOctopus/octopuskit#2]
**Describe the bug**
After trying to run the Quick Start guide steps I'm presented with a build error of `'KeyboardEventComponent' is unavailable in iOS` - This seems to be in the source of the package rather than in the Quick Start files.

**To Reproduce**
1. Follow Quick Start steps
2. Build to iOS device
3. See error

**Expected behavior**
Build to complete without errors

**Desktop (please complete the following information):**
 - OS: macOS 
 - Browser: Safari
 - Version: 10.15.3 (19D76)

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro (12,3)
 - OS: iOS
 - Browser: Safari
 - Version: 13.3.1

**Comment by Harry-Harrison** [comment]
I've been trying to fix this myself, but don't know enough to be able to say I can. I was trying to find a way for it to fail quietly rather than adding keyboard support for iOS.

**Comment by ShinryakuTako** [comment]
Fixed! I've been testing new stuff on macOS (for quicker build times and faster performance) and forgot to wrap the keyboard stuff in conditional compilation hugs. :)

**Comment by Harry-Harrison** [comment]
Awesome, thank you!
