### ISSUE TITLE
[Help] Turning Debug Statements off

### ISSUE THREAD

**Issue by astaranowicz** [InvadingOctopus/octopuskit#3]
Hi,

I followed the instructions for adding this project to mine, however, I don't see a way to turn off the debug statements to the console.

Thanks.

**Comment by ShinryakuTako** [comment]
What a coincidence! I just added some info about customizing the logging system yesterday, thinking that someone might want to know this. 😅

Please see [Tips & Troubleshooting](https://github.com/InvadingOctopus/octopuskit/blob/develop/Documentation/Tips%20%26%20Troubleshooting.md#tips—tricks). 

The logs are all defined in `OctopusKit+Logs.swift` and you can disable them individually by `OctopusKit.logForDebug.isDisabled = true` and so on.

**Comment by astaranowicz** [comment]
AWESOME!
Thank you for the tip!
