### ISSUE TITLE
[Help] Clarity on OKContainerView, OKGameCoordinator, OKViewController

### ISSUE THREAD

**Issue by astaranowicz** [InvadingOctopus/octopuskit#4]
Hi,

Reading over the documentation and I would like some help on the ContainerView, GameCoordinator, and the ViewController.

From the QuickStart Guide, I can see and understand how to use the project that is entirely SwiftUI. 

I created a sample SwiftUI project that follows your Universal code. 
I also have a project that is entirely UIKit and UIViewControllers (not using the storyboard, mostly generating buttons and labels in code). 

I want to combine these two projects together. I cannot change the UIViewController project, however, I can change the SwiftUI OctopusKit project.

In your opinion, what is the best way to integrate these two projects together?
 
Thank you.

**Comment by ShinryakuTako** [comment]
To display a UIKit view or controller inside a SwiftUI hierarchy, you will need to use [`UIViewRepresentable `](https://developer.apple.com/documentation/swiftui/uiviewrepresentable) or [`UIViewControllerRepresentable`](https://developer.apple.com/documentation/swiftui/uiviewcontrollerrepresentable).

To display a SwiftUI view in an UIKit app, you will need to use [`UIHostingController`](https://developer.apple.com/documentation/swiftui/uihostingcontroller).

Please see [WWDC 2019 - Session 231: Integrating SwiftUI](https://developer.apple.com/videos/play/wwdc2019/231/)

**Comment by astaranowicz** [comment]
Great, I took a look over those and it wasn't very clear. 
From the guide:

func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool
{
    try! OctopusKit(gameCoordinator: coordinator)
    return true
}

It seems OctopusKit needs to be instantiated at the top level instead of just inside of a UIViewController.

This is inside of an subclass of OKGameCoordinator:
let gameCoordinator = OKGameCoordinator(
    states: [OKGameState()], // A placeholder for now.
    initialStateClass: OKGameState.self)

How would I use OctopusKit in a UIKit app directly?  That is the part I'm kind of missing. 

Thank you for your help so far. Its a great toolkit.

**Comment by ShinryakuTako** [comment]
You could modify `OctopusKit.swift`, `OKGameCoordinator.swift`, and `OKViewController.swift` in your fork or local copy of this repository to get the exact startup behavior you need.

I'm considering dropping support for the AppKit/UIKit launch cycles and just embracing the new SwiftUI 2.0 "App" projects in Xcode 12, as they're much simpler and more elegant. Of course, combining AppKit/UIKit/SwiftUI will still be possible, as mentioned before.

> 1. How would I use OctopusKit in a UIKit app directly that is not at the top level while still using the SpiritKit and all of the features of OctopusKit?

For your view controller, try this:

```swift
class GameViewController: OKViewController {

    required init?(coder aDecoder: NSCoder) {
        try! OctopusKit(gameCoordinator: MyGameCoordinator())
        super.init(coder: aDecoder)
    }

    required init(gameCoordinator: OKGameCoordinator? = nil) {
        try! super.init(gameCoordinator: MyGameCoordinator())
    }
}
```

At the minimum, your game scene should inherit from `OKScene` to take advantage of the entity, component and systems management boilerplate. Try the `OctopusKit Scene.xctemplate` from the `Templates/Xcode` folder of this package.

You could provide a dummy `OKGameCoordinator` to the scene, and modify your view controller to simply present an `OKScene` without caring about the broader OctopusKit environment.

> 2. How can i re-initialize the OKGameCoordinator so the Singleton can be reset or released when the game isn't being used?

Try modifying the 3 files mentioned above, in the `Sources/Core/Launch` folder, to allow re-initialization.

**Comment by astaranowicz** [comment]
Awesome. Thank you for the feedback. I'll go off your suggestions.  

I was trying to avoid the route of making a fork of your repo as any updates made here might not integrate so well with the changes I make. 

With regards to dropping the support for the UIKit, I think that would make things maybe a bit cleaner. Users would need to  either extend out their existing SwiftUI Apps or just use the UIHostingController as the intermediate between SwiftUI and the ViewControllers.

**Comment by ShinryakuTako** [comment]
@astaranowicz You could also get the behavior of "resetting" your game by having 2 games states:

```swift
let coordinator = OKGameCoordinator(states: [MainState(),
                                             ResetState()],
                                    initialStateClass: ResetState.self)
```

Keep all your functionality inside the `OKScene` associated with `MainState`, then recreate the scene by cycling between the states as needed:

```swift
let coordinator = OctopusKit.shared.gameCoordinator
coordinator.enter(MainState.self)
coordinator.enter(ResetState.self)
```
