### ISSUE TITLE
Swift Tools Version Error using SPM

### ISSUE THREAD

**Issue by chessboy** [InvadingOctopus/octopuskit#5]
**Category:** 'Package Import'

**Describe the bug**
Trying to import my favorite library :) into a new project and getting this error:

package at 'https://github.com/invadingoctopus/octopuskit' @ 4115ff2a63b0df684eca20367d59ffc22906faae is using Swift tools version 5.3.0 but the installed version is 5.2.0

I've updated to Xcode Version 11.6... do I need to upgrade to Swift 5.3 outside of Xcode's normal install?

Thanks for any help!
Rob

**To Reproduce**
1. Start with a new 'SwiftUI' macOS project
2. See error:
```
package at 'https://github.com/invadingoctopus/octopuskit' @ 4115ff2a63b0df684eca20367d59ffc22906faae is using Swift tools version 5.3.0 but the installed version is 5.2.0
```

**Expected behavior**
The package should import without error.

**Screenshots**

<img width="500" alt="Screen Shot 2020-07-26 at 2 08 38 AM" src="https://user-images.githubusercontent.com/15384192/88472813-eea6de00-cee4-11ea-8d0c-e03a7e5c00f4.png">

<img width="685" alt="Screen Shot 2020-07-26 at 2 03 43 AM" src="https://user-images.githubusercontent.com/15384192/88472807-d46d0000-cee4-11ea-96d1-d2a77fe53404.png">

**Build Environment (what you're developing on)**
    - OctopusKit Version: 'develop'
    - macOS Version: '10.15.15'
    - Xcode Version: '11.6 (11E708)'
    - Swift Version:

```swift -version
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin19.5.0
```
 
**Target Device (what you're compiling for)**
    - Device: 'macOS app'
    - Target OS Version: 'e.g. macOS 10.x'

**Additional context**

**Comment by ShinryakuTako** [comment]
Sorry about this! I think you'll need Xcode **12**. I'm not good with maintaining backwards compatibility. 😭

You may also be able to manually edit the `Package.swift` manifest file and change `// swift-tools-version:5.3` to `5.2`, but I'm not sure if that will work with the new features like package resources/assets, so you may have to remove those lines too.

**Comment by chessboy** [comment]
OK, no worries… you may want to specify minimum Swift tools version / minimum XCode version somewhere in the README. Will update tonight. Thanks!

  *   Rob

**Comment by ShinryakuTako** [comment]
> you may want to specify minimum Swift tools version / minimum XCode version somewhere in the README.

Oh that's specified under **Getting Started**, but yeah it's at the bottom of the README. :)

**Comment by ShinryakuTako** [comment]
I'll close this unless the issue persists in the final Xcode 12 build.
