### ISSUE TITLE
GamePadDirectionEvent

### ISSUE THREAD

**Issue by pradeeproark** [InvadingOctopus/octopuskit#9]
Hello,

I find this project very interesting,. I checked the TODO and it said you were planning to work on Gamepad as Inputs. Is this something you are already working on. If not, I would be happy to contribute. But would like some discussion to make sure I do it the proper way as per the conventions set out for other input sources. Can we catch-up on gitter https://gitter.im/ or elsewhere?

- P

**Comment by ShinryakuTako** [comment]
Hi, thanks! I haven't begun work on gamepad input yet (being lazy and waiting for the next beta of Xcode 12).

A hypothetical `GamepadEventComponent` would have to match the current pattern of `KeyboardEventComponent` feeding a `DirectionEventComponent`. 

I don't use Gitter, but you can catch me on the Discord provided in the ReadMe!

**Comment by pradeeproark** [comment]
Thanks. Lesson of the day. Must READ etc. in README. :) catch you on discord.
